import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/styles/libsStyle.ts";
import "@/styles/tailwind.css";
import {MSWComponent} from "@/libs/mocks/config/MSWComponent.client";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
};
export default function RootLayout({children}: Props) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <MSWComponent />
        {children}
      </body>
    </html>
  );
}
