import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/styles/libsStyle.ts";
import "@/styles/tailwind.css";
import {MSWComponent} from "@/libs/mocks/config/MSWComponent.client";
import {ReactNode} from "react";
import {Provider} from "react-redux";
import {store} from "@/store/store";
import Header from "@/components/common/Header";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: ReactNode;
};
export default function RootLayout({children}: Props) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <MSWComponent />
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
